# Generated by Django 2.1.7 on 2019-09-24 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='country',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='payment_option',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='state',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='terms_agreed',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='zip_code',
        ),
    ]
