# Generated by Django 2.2.4 on 2019-09-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('checkout', '0002_auto_20190924_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='checkout',
            name='order_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='checkout',
            name='products',
            field=models.ManyToManyField(to='cart.Cart'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='shipping',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='checkout',
            name='sub_total',
            field=models.FloatField(default=0),
        ),
    ]
