# Generated by Django 2.2.4 on 2019-09-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('checkout', '0004_remove_checkout_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='products',
            field=models.ManyToManyField(to='cart.Cart'),
        ),
    ]
